#!/bin/bash

MANIFEST=git://github.com/crdroidandroid/android.git
BRANCH=11.0

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name ItsVixano
git config --global user.email vixanonew@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# Sync stuffs
cd build/soong && git remote add d https://github.com/SyntatiX-OS/build_soong -f && git cherry-pick 781bd3afedb8891ddbeab6f96555db68ca1a2ad3^..470a3a74636831eb89f3c274897a1483761e9079 && cd ../..
git clone -b lineage-18.1 --depth=1 https://github.com/LineageOS/android_device_motorola_channel/ device/motorola/channel
git clone -b lineage-18.1 --depth=1 https://github.com/LineageOS/android_device_motorola_sdm632-common/ device/motorola/sdm632-common
git clone -b lineage-18.1 --depth=1 https://github.com/LineageOS/android_kernel_motorola_sdm632/ kernel/motorola/sdm632
git clone -b lineage-18.1 --depth=1 https://github.com/TheMuppets/proprietary_vendor_motorola vendor/motorola
git clone -b lineage-18.1 --depth=1 https://github.com/LineageOS/android_hardware_motorola/ hardware/motorola
git clone -b lineage-18.1 --depth=1 https://github.com/LineageOS/android_system_qcom/ system/qcom
git clone -b lineage-18.1 --depth=1 https://github.com/LineageOS/android_external_bson/ external/bson

