#!/bin/bash

MANIFEST=https://github.com/CherishOS/android_manifest
BRANCH=eleven

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name Griffin
git config --global user.email bluedogerino@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# Sync stuffs

git clone -b Cherish-11 --depth=1 https://github.com/GismoBe/device_xiaomi_miatoll device/xiaomi/miatoll
git clone -b Cherish-11 --depth=1 https://github.com/GismoBe/android_vendor_xiaomi_sm6250/ vendor/xiaomi
git clone -b Kang-11 --depth=1 https://github.com/GismoBe/android_kernel_xiaomi_sm6250.git kernel/xiaomi/sm6250

