#!/bin/bash

MANIFEST=repo init -u git://github.com/LineageOS/android.git
BRANCH=lineage-17.1

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name Griffin
git config --global user.email bluedogerino@gmail.com

git clone https://"$GITHUB_TOKEN":x-oauth-basic@github.com/fsalamic/google-git-cookies.git
if [ -e google-git-cookies ]; then
    cd google-git-cookies
    bash setup_cookies.sh
    cd ../
    rm -rf google-git-cookies
else
    echo "google-git-cookies repo not found on your account, see steps on README"
fi

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# Sync stuffs

